ansible_python_interpreter: /usr/bin/python3
ansible_user: mdb
compose_project_name: mdb

drone_admin_user: mariadb-RomanNavrotskiy
drone_admin_token: "{{ drone_admin_token_vault }}"
drone_github_client: "{{ drone_github_client_vault }}"
drone_github_secret: "{{ drone_github_secret_vault }}"
drone_rpc_secret: "{{ drone_rpc_secret_vault }}"

drone_host: "{{ inventory_hostname }}"
drone_proto: http
drone_debug: false

autoscaler_host: "{{ drone_host }}"
autoscaler_proto: "{{ drone_proto }}"
autoscaler_debug: "{{ drone_debug }}"
